# Numpy 기초 익히기

* Numpy Array
    * -동일 타입의 원소
    * -메모리 최적화, 계산 속도 향상
    * -크기(dimension)이 명확하게 정의
    * -전체 연산 가능


## 1. Numpy Array와 Python list의 차이 확인

In [1]:
import numpy as np

In [2]:
# Numpy Array 
ar = np.array([0,1,2,3,4,5,6,7,8,9])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# Python List
ls = [0,1,2,3,4,5,6,7,8,9]
ls

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
# 자료형 비교
print(type(ar), type(ls))

<class 'numpy.ndarray'> <class 'list'>


## 2. 벡터화 연산
배열 객체는 배열의 각 원소에 대한 반복 연산을 하나의 명령어로 처리하는 벡터화 연산을 지원한다.

예제) 여러개의 데이터를 모두 2배 해야 하는 경우

In [5]:
data = [0,1,2,3,4,5,6,7,8,9]

In [6]:
# ① for 반복문 사용

answer = []
for di in data :
    answer.append(2 * di)
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [7]:
# ② 벡터화 연산 사용 = for 반복문 없이 한 번의 연산 가능

x= np.array(data)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
2 * x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
## 자료형이 리스트일 때 정수 곱의 결과는? - 객체의 크기가 정수배만큼 증가

L = [0,1,2,3,4,5,6,7,8,9]
print(2 * L)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [11]:
a = np.array([1,2,3])
b = np.array([10,20,30])

In [12]:
2 * a + b

array([12, 24, 36])

In [13]:
2 * 1 + 10

12

In [14]:
#비교 연산
a == 2

array([False,  True, False])

In [15]:
b > 10

array([False,  True,  True])

In [16]:
#논리 연산 - 논리 곱(AND) 연산 : (TRUE, TRUE) 일 때만 TRUE 를 반환
(a == 2) & (b > 10)

array([False,  True, False])

## 3. 다차원 배열 만들기

### 1. 2차원 배열
ndarray 는 N-dimensional Array의 약자이다. 이름 그대로 1차원 배열 이외에도 2차원 배열, 3차원 배열 등의 다차원 배열 자료 구조를 지원한다. 2차원 배열은 행렬(matrix)이라고 하는데 행렬에서는 가로줄을 행(row)이라고 하고 세로줄을 열(column)이라고 부른다.

다음과 같이 리스트의 리스트(list of list)를 이용하면 2차원 배열을 생성할 수 있다. 안쪽 리스트의 길이는 행렬의 열의 수 즉, 가로 크기가 되고 바깥쪽 리스트의 길이는 행렬의 행의 수, 즉 세로 크기가 된다. 예를 들어 2 x 3 배열은 다음과 같이 만든다.

In [20]:
# ① 2차원 배열

c = np.array([[0,1,2],[3,4,5]])  # 2 x 3 array
c

array([[0, 1, 2],
       [3, 4, 5]])

In [21]:
print(len(c), len(c[0]))  # 행의 개수, 열의 개수

2 3


연습문제 1) NumPy를 사용하여 다음과 같은 행렬을 만든다.

10 20 30 40

50 60 70 80

In [21]:
#답
mat = np.array([[10,20,30,40],[50,60,70,80]])
print(mat)

[[10 20 30 40]
 [50 60 70 80]]


### 2. 3차원 배열
리스트의 리스트의 리스트를 이용하면 3차원 배열도 생성할 수 있다. 크기를 나타낼 때는 가장 바깥쪽 리스트의 길이부터 가장 안쪽 리스트 길이의 순서로 표시한다. 예를 들어 2 x 3 x 4 배열은 다음과 같이 만든다.

In [23]:
# ② 3차원 배열

d = np.array([[[1,2,3,4],
            [5,6,7,8],
            [9,10,11,12]],
            [[11,12,13,14],
            [15,16,17,18],
            [19,20,21,22]]])  # 2 x 3 x 4 array

In [24]:
len(d), len(d[0]), len(d[0][0])  # 3차원 배열의 행, 열, 깊이

(2, 3, 4)

## 4. 배열의 인덱싱
### 1. 1차원 배열의 인덱싱

파이썬은 R과는 다르게 0부터 시작

In [28]:
a = np.array([10,20,30,40,50])
a

array([10, 20, 30, 40, 50])

In [29]:
a[2]   # 3번째 원소 추출

30

In [30]:
a[-1]  # 뒤에서부터 센다.

50

### 2. 2차원 배열의 인덱싱

In [31]:
a = np.array([[0,1,2],[3,4,5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [28]:
# 배열명[행,열]

a[0,0]  # 첫번째 행의 첫번째 열

0

In [29]:
a[0,1] # 첫번째 행의 두번째 열

1

In [30]:
a[-1,-1] # 마지막 행의 마지막 열

5

## 5. 배열 슬라이싱
배열 객체로 구현한 다차원 배열의 원소 중 복수 개를 접근하려면 일반적인 파이썬 슬라이싱(slicing)과 comma(,)를 함께 사용하면 된다.

In [31]:
a = np.array([[0,1,2,3],[4,5,6,7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [32]:
a[0,:]  # 첫번째 행 전체

array([0, 1, 2, 3])

In [33]:
a[:,0] # 첫번째 열 전체

array([0, 4])

In [34]:
a[1,1:] # 두번째 행의 두번째 열부터 끝열까지

array([5, 6, 7])

연습문제 2) 다음 행렬과 같은 행렬이 있다.

m = np.array(<br>
[[ 0,  1,  2,  3,  4],<br>
                [ 5,  6,  7,  8,  9],<br>
                [10, 11, 12, 13, 14]])<br>
              
1. 이 행렬에서 값 7 을 인덱싱한다.
2. 이 행렬에서 값 14 을 인덱싱한다.
3. 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
4. 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
5. 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.

In [35]:
m = np.array([[ 0,  1,  2,  3,  4],
              [ 5,  6,  7,  8,  9],
              [10, 11, 12, 13, 14]])
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [36]:
# 1. 이 행렬에서 값 7 을 인덱싱한다.
m[1,2]

7

In [37]:
# 2. 이 행렬에서 값 14 을 인덱싱한다.
m[2,4]

14

In [40]:
# 3. 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
m[1,1:3] # 파이썬의 n:m 연산은 n부터 m-1 까지를 의미

array([6, 7])

In [41]:
# 4. 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
m[1:3,2]

array([ 7, 12])

In [42]:
# 5. 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.
m[0:2,3:5]

array([[3, 4],
       [8, 9]])

## 6. 배열 인덱싱 - 팬시 인덱싱(fancy indexing)
NumPy 배열 객체의 또다른 강력한 기능은 팬시 인덱싱(fancy indexing)이라고도 부르는 배열 인덱싱(array indexing) 방법이다. 인덱싱이라는 이름이 붙었지만 사실은 데이터베이스의 질의(Query) 기능을 수행한다. 배열 인덱싱에서는 대괄호(Bracket, [])안의 인덱스 정보로 숫자나 슬라이스가 아니라 위치 정보를 나타내는 또 다른 ndarray 배열을 받을 수 있다. 여기에서는 이 배열을 편의상 인덱스 배열이라고 부르겠다. 배열 인덱싱의 방식에은 불리안(Boolean) 배열 방식과 정수 배열 방식 두가지가 있다. <br><br>
1. 불리안 배열 인덱싱 <br>
먼저 불리안 배열 인덱싱 방식은 인덱스 배열의 원소가 True, False 두 값으로만 구성되며 인덱스 배열의 크기가 원래 ndarray 객체의 크기와 같아야 한다.

예제 ) 배열 [0,1,2,3,4,5,6,7,8,9] 에서 짝수만 가져오자.

In [43]:
# ① True, False 직접 할당
a = np.array([0,1,2,3,4,5,6,7,8,9])
idx = np.array([True, False, True, False, True,
               False, True, False, True, False])  # 짝수번째에 True값
a[idx] # idx가 True인 인덱스에 해당하는 값만 반환

array([0, 2, 4, 6, 8])

In [44]:
# ② 수식 이용 
a % 2 # 짝수 판별 연산 : 2로 나누었을 때 나머지가 0이면 짝수, 1이면 홀수

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [45]:
a % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [46]:
a[a % 2 == 0]

array([0, 2, 4, 6, 8])

    2. 정수 배열 인덱싱 
    인덱스 배열의 원소 각각이 원래 ndarray 객체 원소 하나를 가리키는 인덱스 정수이여야 한다

In [47]:
# 1차원 배열일 때
a = np.array([11,22,33,44,55,66,77,88,99])
idx = np.array([0,2,4,6,8]) # 첫번째, 세번째, 다섯번째, 일곱번째, 아홉번째 원소 가져오겠다
a[idx]

array([11, 33, 55, 77, 99])

In [32]:
# 2차원 배열일 때
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
a[:,[True, False, True, False]]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [34]:
bool_idx = (a % 2 ==1)
print(bool_idx)

[[ True False  True False]
 [ True False  True False]
 [ True False  True False]]


In [37]:
a[bool_idx]

array([ 1,  3,  5,  7,  9, 11])

In [36]:
a[a%2==1]

array([ 1,  3,  5,  7,  9, 11])

In [62]:
a[[2,0,1],:] # 세번째, 첫번째, 두번째 행 순으로 출력

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

연습문제 3)
다음 행렬과 같은 배열이 있다.<br>
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,  <br>
<tab> <tab>  11, 12, 13, 14, 15, 16, 17, 18, 19, 20]) <br>
1. 이 배열에서 3의 배수를 찾아라.
2. 이 배열에서 4로 나누면 1이 남는 수를 찾아라.
3. 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.

In [63]:
# 1. 이 배열에서 3의 배수를 찾아라.

x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
              11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [65]:
idx_x = (x % 3 == 0)
idx_x

array([False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False])

In [66]:
x[idx_x]

array([ 3,  6,  9, 12, 15, 18])

In [67]:
x[x % 3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [68]:
# 2. 이 배열에서 4로 나누면 1이 남는 수를 찾아라.

x[x % 4 == 1]

array([ 1,  5,  9, 13, 17])

In [81]:
# 3. 이 배열에서 3으로 나누면 나누어떨어지고 4로 나누면 1이 남는 수를 찾아라.

bool1 = x % 3 == 0
bool2 = x % 4 == 1

In [84]:
bool1

array([False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False])

In [85]:
bool2

array([ True, False, False, False,  True, False, False, False,  True,
       False, False, False,  True, False, False, False,  True, False,
       False, False])

In [89]:
np.logical_and(bool1,bool2)  # bool1이면서 bool2인 원소를 True로 반환(논리곱!)

array([False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [88]:
x[np.logical_and(bool1,bool2)]

array([9])

## 그 외 NumPy 함수들

### 배열 생성
* zero, ones
* zeros_ike, ones_like
* empty
* arrange
* linspace, logspace
* rand, randn

1. zero, ones

In [90]:
# 크기가 정해져 있고 모든 값이 0인 배열을 생성하려면 zeros 명령을 사용한다. 
# 인수로는 배열을 크기를 뜻하는 정수를 넣는다.

a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [91]:
b = np.zeros((2, 3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [92]:
#0이 아닌 1로 초기화된 배열을 생성하려면 ones 명령을 사용한다.

e = np.ones((2, 3, 4), dtype="i8")
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

2. zero_like, ones_like

In [93]:
# 만약 크기를 튜플로 명시하지 않고 다른 배열과 같은 크기의 배열을 생성하고 싶다면 
# ones_like, zeros_like 명령을 사용한다.

f = np.ones_like(b, dtype="f")
f

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

3.empty

배열의 크기가 커지면 배열을 초기화하는데도 시간이 걸린다. 이 시간을 단축하려면 배열을 생성만 하고 특정한 값으로 초기화를 하지 않는 empty 명령을 사용할 수 있다. empty 명령으로 생성된 배열에는 기존에 메모리에 저장되어 있던 값이 있으므로 배열의 원소의 값을 미리 알 수 없다.

In [38]:
l = np.empty((4, 3))
l

array([[9.27187875e-312, 2.47032823e-322, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 1.16095484e-028],
       [1.07441485e+160, 5.02036163e+175, 8.93176403e+271],
       [4.98131536e+151, 6.35296669e-062, 1.04120391e-042]])

4. arrange

arange 명령은 NumPy 버전의 range 명령이라고 볼 수 있다. 특정한 규칙에 따라 증가하는 수열을 만든다.

In [98]:
np.arange(10) # 0 .. n-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
np.arange(3, 21, 2)  # 시작, 끝(포함하지 않음), 단계

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

5. linspace , logspace

명령이나 logspace 명령은 선형 구간 혹은 로그 구간을 지정한 구간의 수만큼 분할한다.

In [100]:
np.linspace(0, 100, 5)  # 시작, 끝(포함), 갯수

array([  0.,  25.,  50.,  75., 100.])

In [101]:
np.logspace(0.1, 1, 10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

### 전치 연산

2차원 배열의 전치(transpose) 연산은 행과 열을 바꾸는 작업이다. 이는 배열의 T 속성으로 구할 수 있다. 메서드가 아닌 속성이라는 점에 유의 한다.

In [102]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [103]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

### 배열의 크기 변형

일단 만들어진 배열의 내부 데이터는 보존한 채로 형태만 바꾸려면 reshape 명령이나 메서드를 사용한다. 예를 들어 12개의 원소를 가진 1차원 행렬은 3x4 형태의 2차원 행렬로 만들 수 있다.

In [104]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [105]:
b = a.reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])


사용하는 원소의 갯수가 정해저 있기 때문에 reshape 명령의 형태 튜플의 원소 중 하나는 -1이라는 숫자로 대체할 수 있다. -1을 넣으면 해당 숫자는 다를 값에서 계산되어 사용된다.

In [106]:
a.reshape(3, -1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [107]:
a.reshape(2, 2, -1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [108]:
a.reshape(2, -1, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

다차원 배열을 무조건 1차원으로 펼치기 위해서는 flatten 나 ravel 메서드를 사용한다.

In [109]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [110]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


배열 사용에서 주의할 점은 길이가 5인 1차원 배열과 행, 열의 갯수가 (5,1)인 2차원 배열 또는 행, 열의 갯수가 (1, 5)인 2차원 배열은 데이터가 같아도 엄연히 다른 객체라는 점이다.

In [111]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [112]:
x.reshape(1, 5)

array([[0, 1, 2, 3, 4]])

In [113]:
x.reshape(5, 1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [114]:
x[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

### 배열 연결

행의 수나 열의 수가 같은 두 개 이상의 배열을 연결하여(concatenate) 더 큰 배열을 만들 때는 다음과 같은 명령을 사용한다.

* hstack
* vstack
* dstack
* stack
* r_
* c_
* tile


hstack 명령은 행의 수가 같은 두 개 이상의 배열을 옆으로 연결하여 열의 수가 더 많은 배열을 만든다. 연결할 배열은 하나의 리스트에 담아야 한다.

In [115]:
a1 = np.ones((2, 3))
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [116]:
a2 = np.zeros((2, 2))
a2

array([[0., 0.],
       [0., 0.]])

In [117]:
np.hstack([a1, a2])

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])


vstack 명령은 열의 수가 같은 두 개 이상의 배열을 위아래로 연결하여 행의 수가 더 많은 배열을 만든다. 연결할 배열은 마찬가지로 하나의 리스트에 담아야 한다.

In [118]:
b1 = np.ones((2, 3))
b1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [119]:
b2 = np.zeros((3, 3))
b2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [120]:
np.vstack([b1, b2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])


dstack 명령은 제3의 축 즉, 행이나 열이 아닌 깊이(depth) 방향으로 배열을 합친다. 가장 안쪽의 원소의 차원이 증가한다. 즉 가장 내부의 숫자 원소가 배열이 된다. shape 정보로 보자면 가장 끝에 값이 2인 차원이 추가되는 것이다.이 예제의 경우에는 shape 변화가 2개의 (3 x 4) -> 1개의 (3 x 4 x 2)가 된다.

In [121]:
c1 = np.ones((3, 4))
c1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [122]:
c2 = np.zeros((3, 4))
c2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [123]:
np.dstack([c1, c2])

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [124]:
(np.dstack([c1, c2])).shape

(3, 4, 2)

stack 명령은 dstack의 기능을 확장한 것으로 dstack처럼 마지막 차원으로 연결하는 것이 아니라 사용자가 지정한 차원(축으로) 배열을 연결한다. axis 인수(디폴트 0)를 사용하여 연결후의 회전 방향을 정한다. 디폴트 인수값은 0이고 가장 앞쪽에 차원이 생성된다. 즉, 배열 두 개가 겹치게 되므로 연결하고자 하는 배열들의 크기가 모두 같아야 한다.

다음 예에서는 axis=0 이므로 가장 값에 값이 2인 차원이 추가된다. 즉, shape 변화는 2개의 (3 x 4) -> 1개의 (2 x 3 x 4) 이다..

In [125]:
c = np.stack([c1, c2])
c

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [126]:
c.shape

(2, 3, 4)

axis 인수가 1이면 두번째 차원으로 새로운 차원이 삽입된다. 다음 예에서 즉, shape 변화는 2개의 (3 x 4) -> 1개의 (3 x 2 x 4) 이다

In [127]:
c = np.stack([c1, c2], axis=1)
c

array([[[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]]])

In [128]:
c.shape

(3, 2, 4)

r_ 메서드는 hstack 명령과 비슷하게 배열을 좌우로 연결한다. 다만 메서드임에도 불구하고 소괄호(parenthesis, ())를 사용하지 않고 인덱싱과 같이 대괄호(bracket, [])를 사용한다. 이런 특수 메서드를 인덱서(indexer)라고 한다.

In [129]:
np.r_[np.array([1, 2, 3]), np.array([4, 5, 6])]

array([1, 2, 3, 4, 5, 6])

c_ 메서드는 배열의 차원을 증가시킨 후 좌우로 연결한다. 만약 1차원 배열을 연결하면 2차원 배열이 된다.

In [130]:
np.c_[np.array([1, 2, 3]), np.array([4, 5, 6])]

array([[1, 4],
       [2, 5],
       [3, 6]])


tile 명령은 동일한 배열을 반복하여 연결한다.

In [131]:
a = np.array([[0, 1, 2], [3, 4, 5]])
np.tile(a, 2)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [132]:
np.tile(a, (3, 2))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])